export const products = [
  {
    Id: 1,
    Name: "Boat Airdopes 111",
    Price: 1099,
    Category: "Airdopes",
    Image: [
      "/assets/electronics/boAt Airdopes 111 1.webp",
      "/assets/electronics/boAt Airdopes 111 2.webp",
      "/assets/electronics/boAt Airdopes 111 3.webp",
      "/assets/electronics/boAt Airdopes 111 4.webp",
    ],
    Count: 1,
    Heading:
      "boAt Airdopes 131 with upto 60 hours and ASAP Charge Bluetooth  (Active, True Wireless)",
    Brand: "Boat",
    Type: "Electronics",
    Trending: true,
    Rating: "4.3",
    Description:
      "Experience audio fun endlessly with the Airdopes 181 Pro TWS Earbuds. Tap your feet to your playlist on repeat as 100 hours of massive playtime has got your back",
  },
  {
    Id: 2,
    Name: "Boat Airdopes 201",
    Price: 1499,
    Category: "Airdopes",
    Image: [
      "/assets/electronics/boAt Airdopes 201 1.webp",
      "/assets/electronics/boAt Airdopes 201 2.webp",
      "/assets/electronics/boAt Airdopes 201 3.webp",
      "/assets/electronics/boAt Airdopes 201 4.webp",
    ],
    Count: 1,
    Heading:
      "boAt Airdopes 131 with upto 60 hours and ASAP Charge Bluetooth  (Active, True Wireless)",
    Brand: "Boat",
    Type: "Electronics",
    Trending: false,
    Rating: "4.5",
    Description:
      "Experience audio fun endlessly with the Airdopes 181 Pro TWS Earbuds. Tap your feet to your playlist on repeat as 100 hours of massive playtime has got your back",
  },
  {
    Id: 3,
    Name: "Boat Airdopes 381",
    Price: 1399,
    Category: "Airdopes",
    Image: [
      "/assets/electronics/boAt Airdopes 381 1.webp",
      "/assets/electronics/boAt Airdopes 381 2.webp",
      "/assets/electronics/boAt Airdopes 381 3.webp",
      "/assets/electronics/boAt Airdopes 381 4.webp",
    ],
    Count: 1,
    Heading:
      "boAt Airdopes 131 with upto 60 hours and ASAP Charge Bluetooth  (Active, True Wireless)",
    Brand: "Boat",
    Type: "Electronics",
    Trending: false,
    Rating: "3.8",
    Description:
      "Experience audio fun endlessly with the Airdopes 181 Pro TWS Earbuds. Tap your feet to your playlist on repeat as 100 hours of massive playtime has got your back",
  },
  {
    Id: 4,
    Name: "Boat TRebel Airdopes 431",
    Price: 1999,
    Category: "Airdopes",
    Image: [
      "/assets/electronics/boAt TRebel Airdopes 431 1.webp",
      "/assets/electronics/boAt TRebel Airdopes 431 2.webp",
      "/assets/electronics/boAt TRebel Airdopes 431 3.webp",
      "/assets/electronics/boAt TRebel Airdopes 431 4.webp",
    ],
    Count: 1,
    Heading:
      "boAt Airdopes 131 with upto 60 hours and ASAP Charge Bluetooth  (Active, True Wireless)",
    Brand: "Boat",
    Type: "Electronics",
    Trending: false,
    Rating: "3.9",
    Description:
      "Experience audio fun endlessly with the Airdopes 181 Pro TWS Earbuds. Tap your feet to your playlist on repeat as 100 hours of massive playtime has got your back",
  },
  {
    Id: 5,
    Name: "Boat Cosmos Pro",
    Price: 3399,
    Category: "Watch",
    Image: [
      "/assets/electronics/boAt Cosmos Pro 1.webp",
      "/assets/electronics/boAt Cosmos Pro 2.webp",
      "/assets/electronics/boAt Cosmos Pro 3.webp",
      "/assets/electronics/boAt Cosmos Pro 4.webp",
    ],
    Count: 1,
    Heading: "boAt Cosmos PRO Smartwatch  (Blue Strap, 1.78 AMOLED DISPLAY)",
    Brand: "Boat",
    Type: "Electronics",
    Trending: true,
    Rating: "4.0",
    Description:
      "You can stay connected to the digital world at all times with the help of the Boult Drift+ Smartwatch. It features a large touchscreen HD display of up to 4.69 cm (1.85), offering up to 500 nits of brightness for clear and vibrant visuals",
  },
  {
    Id: 6,
    Name: "boAt Wave Beat",
    Price: 3399,
    Category: "Watch",
    Image: [
      "/assets/electronics/boAt Wave Beat 1.webp",
      "/assets/electronics/boAt Wave Beat 2.webp",
      "/assets/electronics/boAt Wave Beat 3.webp",
      "/assets/electronics/boAt Wave Beat 4.webp",
    ],
    Count: 1,
    Heading:
      "boAt Wave Beat Call with 4.64 cm(1.69) HD Display,BT Calling, Watch Face Studio Smartwatch  (Deep Blue Strap, Free Size))",
    Brand: "Boat",
    Type: "Electronics",
    Trending: false,
    Rating: "4.1",
    Description:
      "You can stay connected to the digital world at all times with the help of the Boult Drift+ Smartwatch. It features a large touchscreen HD display of up to 4.69 cm (1.85), offering up to 500 nits of brightness for clear and vibrant visuals",
  },
  {
    Id: 7,
    Name: "boAt Wave Call",
    Price: 2999,
    Category: "Watch",
    Image: [
      "/assets/electronics/boAt Wave Call 1.webp",
      "/assets/electronics/boAt Wave Call 2.webp",
      "/assets/electronics/boAt Wave Call 3.webp",
      "/assets/electronics/boAt Wave Call 4.webp",
    ],
    Count: 1,
    Heading:
      "boAt Wave Beat Call with 4.64 cm(1.69) HD Display,BT Calling, Watch Face Studio Smartwatch  (Deep Blue Strap, Free Size))",
    Brand: "Boat",
    Type: "Electronics",
    Trending: true,
    Rating: "4.2",
    Description:
      "You can stay connected to the digital world at all times with the help of the Boult Drift+ Smartwatch. It features a large touchscreen HD display of up to 4.69 cm (1.85), offering up to 500 nits of brightness for clear and vibrant visuals",
  },
  {
    Id: 8,
    Name: "boAt Wave Select",
    Price: 5499,
    Category: "Watch",
    Image: [
      "/assets/electronics/boAt Wave Select 1.webp",
      "/assets/electronics/boAt Wave Select 2.webp",
      "/assets/electronics/boAt Wave Select 3.webp",
      "/assets/electronics/boAt Wave Select 4.webp",
    ],
    Count: 1,
    Heading:
      "boAt Wave Beat Call with 4.64 cm(1.69) HD Display,BT Calling, Watch Face Studio Smartwatch  (Deep Blue Strap, Free Size))",
    Brand: "Boat",
    Type: "Electronics",
    Trending: false,
    Rating: "4.6",
    Description:
      "You can stay connected to the digital world at all times with the help of the Boult Drift+ Smartwatch. It features a large touchscreen HD display of up to 4.69 cm (1.85), offering up to 500 nits of brightness for clear and vibrant visuals",
  },
  {
    Id: 9,
    Name: "boAt Rockerz 400",
    Price: 999,
    Category: "Headphones",
    Image: [
      "/assets/electronics/boAt Rockerz 400 1.webp",
      "/assets/electronics/boAt Rockerz 400 2.webp",
      "/assets/electronics/boAt Rockerz 400 3.webp",
      "/assets/electronics/boAt Rockerz 400 4.webp",
    ],
    Count: 1,
    Heading:
      "boAt Rockerz 450 w/ 40mm Drivers, 15 HRS Playback, Soft Padded Earcups Bluetooth  (Luscious Black, On the Ear)",
    Brand: "Boat",
    Type: "Electronics",
    Trending: false,
    Rating: "4.5",
    Description:
      "Are you looking for a headset that features eye-catching aesthetics and dual modes? If yes, bring home the boAt Rockerz 450 that has an AUX-mode as well as the Bluetooth connectivity feature.",
  },
  {
    Id: 10,
    Name: "boAt Rockerz 558",
    Price: 1199,
    Category: "Headphones",
    Image: [
      "/assets/electronics/boAt Rockerz 558 1.webp",
      "/assets/electronics/boAt Rockerz 558 2.webp",
      "/assets/electronics/boAt Rockerz 558 3.webp",
      "/assets/electronics/boAt Rockerz 558 4.webp",
    ],
    Count: 1,
    Heading:
      "boAt Rockerz 450 w/ 40mm Drivers, 15 HRS Playback, Soft Padded Earcups Bluetooth  (Luscious Black, On the Ear)",
    Brand: "Boat",
    Type: "Electronics",
    Trending: false,
    Rating: "3.8",
    Description:
      "Are you looking for a headset that features eye-catching aesthetics and dual modes? If yes, bring home the boAt Rockerz 450 that has an AUX-mode as well as the Bluetooth connectivity feature",
  },
  {
    Id: 11,
    Name: "boAt Rockerz 518",
    Price: 1299,
    Category: "Headphones",
    Image: [
      "/assets/electronics/boAt Rockerz 518 1.webp",
      "/assets/electronics/boAt Rockerz 518 2.webp",
      "/assets/electronics/boAt Rockerz 518 3.webp",
      "/assets/electronics/boAt Rockerz 518 4.webp",
    ],
    Count: 1,
    Heading:
      "boAt Rockerz 450 w/ 40mm Drivers, 15 HRS Playback, Soft Padded Earcups Bluetooth  (Luscious Black, On the Ear)",
    Brand: "Boat",
    Type: "Electronics",
    Trending: false,
    Rating: "4.1",
    Description:
      "Are you looking for a headset that features eye-catching aesthetics and dual modes? If yes, bring home the boAt Rockerz 450 that has an AUX-mode as well as the Bluetooth connectivity feature.",
  },
  {
    Id: 12,
    Name: "boAt TRebel Rockerz 450",
    Price: 1799,
    Category: "Headphones",
    Image: [
      "/assets/electronics/boAt TRebel Rockerz 450 1.webp",
      "/assets/electronics/boAt TRebel Rockerz 450 2.webp",
      "/assets/electronics/boAt TRebel Rockerz 450 3.webp",
      "/assets/electronics/boAt TRebel Rockerz 450 4.webp",
    ],
    Count: 1,
    Heading:
      "boAt Rockerz 450 w/ 40mm Drivers, 15 HRS Playback, Soft Padded Earcups Bluetooth  (Luscious Black, On the Ear)",
    Brand: "Boat",
    Type: "Electronics",
    Trending: true,
    Rating: "2.5",
    Description:
      "Are you looking for a headset that features eye-catching aesthetics and dual modes? If yes, bring home the boAt Rockerz 450 that has an AUX-mode as well as the Bluetooth connectivity feature.",
  },
  {
    Id: 13,
    Name: "SAMSUNG Galaxy A14 5G",
    Price: 12999,
    Category: "Mobile",
    Image: [
      "/assets/electronics/SAMSUNG Galaxy A14 5G (Dark Red, 64 GB) (4 GB RAM) 1.webp",
      "/assets/electronics/SAMSUNG Galaxy A14 5G (Dark Red, 64 GB) (4 GB RAM) 2.webp",
      "/assets/electronics/SAMSUNG Galaxy A14 5G (Dark Red, 64 GB) (4 GB RAM) 3.webp",
      "/assets/electronics/SAMSUNG Galaxy A14 5G (Dark Red, 64 GB) (4 GB RAM) 4.webp",
    ],
    Count: 1,
    Heading:
      "boAt Rockerz 450 w/ 40mm Drivers, 15 HRS Playback, Soft Padded Earcups Bluetooth  (Luscious Black, On the Ear)",
    Brand: "Samsung",
    Type: "Electronics",
    Trending: true,
    Rating: "5",
    Description:
      "With the feature-rich Samsung Galaxy A14 5G smartphone, you can multitask without lag and have flawless connectivity. ",
  },
  {
    Id: 14,
    Name: "SAMSUNG Galaxy F23 5G",
    Price: 12999,
    Category: "Mobile",
    Image: [
      "/assets/electronics/SAMSUNG Galaxy F23 5G (Aqua Blue, 128 GB) (6 GB RAM) 1.webp",
      "/assets/electronics/SAMSUNG Galaxy F23 5G (Aqua Blue, 128 GB) (6 GB RAM) 1.webp",
      "/assets/electronics/SAMSUNG Galaxy F23 5G (Aqua Blue, 128 GB) (6 GB RAM) 1.webp",
      "/assets/electronics/SAMSUNG Galaxy F23 5G (Aqua Blue, 128 GB) (6 GB RAM) 1.webp",
    ],
    Count: 1,
    Heading: "SAMSUNG Galaxy A14 5G (Dark Red, 128 GB)  (6 GB RAM)#JustHere",
    Brand: "Samsung",
    Type: "Electronics",
    Trending: true,
    Rating: "4.0",
    Description:
      "With the feature-rich Samsung Galaxy A14 5G smartphone, you can multitask without lag and have flawless connectivity",
  },
  {
    Id: 15,
    Name: "SAMSUNG Galaxy M53 5G",
    Price: 15999,
    Category: "Mobile",
    Image: [
      "/assets/electronics/SAMSUNG Galaxy M53 5G (Mystique Green, 128 GB) (8 GB RAM) 1.webp",
      "/assets/electronics/SAMSUNG Galaxy M53 5G (Mystique Green, 128 GB) (8 GB RAM) 2.webp",
      "/assets/electronics/SAMSUNG Galaxy M53 5G (Mystique Green, 128 GB) (8 GB RAM) 3.webp",
      "/assets/electronics/SAMSUNG Galaxy M53 5G (Mystique Green, 128 GB) (8 GB RAM) 4.webp",
    ],
    Count: 1,
    Heading: "SAMSUNG Galaxy A14 5G (Dark Red, 128 GB)  (6 GB RAM)#JustHere",
    Brand: "Samsung",
    Type: "Electronics",
    Trending: false,
    Rating: "3.8",
    Description:
      "With the feature-rich Samsung Galaxy A14 5G smartphone, you can multitask without lag and have flawless connectivity",
  },
  {
    Id: 16,
    Name: "realme 7 Pro",
    Price: 8999,
    Category: "Mobile",
    Image: [
      "/assets/electronics/realme 7 Pro (Mirror Silver, 128 GB) (6 GB RAM) 1.webp",
      "/assets/electronics/realme 7 Pro (Mirror Silver, 128 GB) (6 GB RAM) 2.webp",
      "/assets/electronics/realme 7 Pro (Mirror Silver, 128 GB) (6 GB RAM) 3.webp",
      "/assets/electronics/realme 7 Pro (Mirror Silver, 128 GB) (6 GB RAM) 4.webp",
    ],
    Count: 1,
    Heading: "REDMI 13c 5G (Startrail Silver, 128 GB)  (6 GB RAM)",
    Brand: "Realme",
    Type: "Electronics",
    Trending: false,
    Rating: "4.9",
    Description:
      "With the feature-rich Realme 13c 5g silver smartphone, you can multitask without lag and have flawless connectivity. ",
  },
  {
    Id: 17,
    Name: "Men's Jacket",
    Price: 999,
    Category: "Jacket",
    Image: [
      "/assets/fashion/BlackJacket-1.webp",
      "/assets/fashion/BlackJacket-2.webp",
      "/assets/fashion/BlackJacket-3.webp",
      "/assets/fashion/BlackJacket-4.webp",
    ],
    Count: 1,
    Heading: "Men Solid Bomber Jacket",
    Brand: "Sparks",
    Type: "Fashion",
    Trending: true,
    Rating: "4.8",
    Description:
      "Stay warm and fashionable with our premium men's jacket. Designed for comfort and versatility, this jacket is crafted from high-quality materials to keep you cozy during chilly days",
  },
  {
    Id: 18,
    Name: "Men's Jacket",
    Price: 1199,
    Category: "Jacket",
    Image: [
      "/assets/fashion/BrownJacket-1.webp",
      "/assets/fashion/BrownJacket-2.webp",
      "/assets/fashion/BrownJacket-3.webp",
      "/assets/fashion/BrownJacket-4.webp",
    ],
    Count: 1,
    Heading: "Men Solid Bomber Jacket",
    Brand: "Sparks",
    Type: "Fashion",
    Trending: false,
    Rating: "5.0",
    Description:
      "Stay warm and fashionable with our premium men's jacket. Designed for comfort and versatility, this jacket is crafted from high-quality materials to keep you cozy during chilly days.",
  },
  {
    Id: 19,
    Name: "Men's Jacket",
    Price: 799,
    Category: "Jacket",
    Image: [
      "/assets/fashion/WhiteGrayJacket-1.webp",
      "/assets/fashion/WhiteGrayJacket-2.webp",
      "/assets/fashion/WhiteGrayJacket-3.webp",
      "/assets/fashion/WhiteGrayJacket-4.webp",
    ],
    Count: 1,
    Heading: "Men Solid Bomber Jacket",
    Brand: "Mufti",
    Type: "Fashion",
    Trending: false,
    Rating: "3.2",
    Description:
      "Stay warm and fashionable with our premium men's jacket. Designed for comfort and versatility, this jacket is crafted from high-quality materials to keep you cozy during chilly days.",
  },
  {
    Id: 20,
    Name: "Men's Jacket",
    Price: 899,
    Category: "Jacket",
    Image: [
      "/assets/fashion/YelloishJacket-1.webp",
      "/assets/fashion/YelloishJacket-2.webp",
      "/assets/fashion/YelloishJacket-3.webp",
      "/assets/fashion/YelloishJacket-4.webp",
    ],
    Count: 1,
    Heading: "Men Solid Bomber Jacket",
    Brand: "Mufti",
    Type: "Fashion",
    Trending: false,
    Rating: "3.0",
    Description:
      "Stay warm and fashionable with our premium men's jacket. Designed for comfort and versatility, this jacket is crafted from high-quality materials to keep you cozy during chilly days.",
  },
  {
    Id: 21,
    Name: "Denim Jacket",
    Price: 2290,
    Category: "Denim",
    Image: [
      "/assets/fashion/DenimBlack-1.webp",
      "/assets/fashion/DenimBlack-2.webp",
      "/assets/fashion/DenimBlack-3.webp",
      "/assets/fashion/DenimBlack-4.webp",
    ],
    Count: 1,
    Heading: "Men Washed Denim Jacket",
    Brand: "Sparks",
    Type: "Fashion",
    Trending: true,
    Rating: "3.3",
    Description:
      "Stay warm and fashionable with our premium men's jacket. Designed for comfort and versatility, this jacket is crafted from high-quality materials to keep you cozy during chilly days.",
  },
  {
    Id: 22,
    Name: "Denim Jackets",
    Price: 1899,
    Category: "Denim",
    Image: [
      "/assets/fashion/DenimBlue-1.webp",
      "/assets/fashion/DenimBlue-2.webp",
      "/assets/fashion/DenimBlue-3.webp",
      "/assets/fashion/DenimBlue-4.webp",
    ],
    Count: 1,
    Heading: "Men Washed Denim Jacket",
    Brand: "Sparks",
    Type: "Fashion",
    Trending: false,
    Rating: "2.9",
    Description:
      "Stay warm and fashionable with our premium men's jacket. Designed for comfort and versatility, this jacket is crafted from high-quality materials to keep you cozy during chilly days.",
  },
  {
    Id: 23,
    Name: "Denim Jackets",
    Price: 1499,
    Category: "Denim",
    Image: [
      "/assets/fashion/DenimBrown-1.webp",
      "/assets/fashion/DenimBrown-2.webp",
      "/assets/fashion/DenimBrown-3.webp",
      "/assets/fashion/DenimBrown-4.webp",
    ],
    Count: 1,
    Heading: "Men Washed Denim Jacket",
    Brand: "Mufti",
    Type: "Fashion",
    Trending: false,
    Rating: "3.9",
    Description:
      "Stay warm and fashionable with our premium men's jacket. Designed for comfort and versatility, this jacket is crafted from high-quality materials to keep you cozy during chilly days.",
  },
  {
    Id: 24,
    Name: "Denim Jackets",
    Price: 2899,
    Category: "Denim",
    Image: [
      "/assets/fashion/DenimGray-1.webp",
      "/assets/fashion/DenimGray-2.webp",
      "/assets/fashion/DenimGray-3.webp",
      "/assets/fashion/DenimGray-4.webp",
    ],
    Count: 1,
    Heading: "Men Washed Denim Jacket",
    Brand: "Sparks",
    Type: "Fashion",
    Trending: true,
    Rating: "2.9",
    Description:
      "Stay warm and fashionable with our premium men's jacket. Designed for comfort and versatility, this jacket is crafted from high-quality materials to keep you cozy during chilly days.",
  },
  {
    Id: 25,
    Name: "Regular Jeans",
    Price: 699,
    Category: "Jeans",
    Image: [
      "/assets/fashion/RegularJeansBlack-1.webp",
      "/assets/fashion/RegularJeansBlack-2.webp",
      "/assets/fashion/RegularJeansBlack-3.webp",
      "/assets/fashion/RegularJeansBlack-4.webp",
    ],
    Count: 1,
    Heading: "Men Loose Fit Mid Rise Blue Jeans",
    Brand: "Mufti",
    Type: "Fashion",
    Trending: false,
    Rating: "3.5",
    Description:
      "Stay warm and fashionable with our premium men's jacket. Designed for comfort and versatility, this jacket is crafted from high-quality materials to keep you cozy during chilly days.",
  },
  {
    Id: 26,
    Name: "Regular Jeans",
    Price: 999,
    Category: "Jeans",
    Image: [
      "/assets/fashion/RegularJeansBlue-1.webp",
      "/assets/fashion/RegularJeansBlue-2.webp",
      "/assets/fashion/RegularJeansBlue-3.webp",
      "/assets/fashion/RegularJeansBlue-4.webp",
    ],
    Count: 1,
    Heading: "Men Loose Fit Mid Rise Blue Jeans",
    Brand: "Sparks",
    Type: "Fashion",
    Trending: false,
    Rating: "3.1",
    Description:
      "Stay warm and fashionable with our premium men's jacket. Designed for comfort and versatility, this jacket is crafted from high-quality materials to keep you cozy during chilly days.",
  },
  {
    Id: 27,
    Name: "Regular Jeans",
    Price: 1199,
    Category: "Jeans",
    Image: [
      "/assets/fashion/RegularJeans-1.webp",
      "/assets/fashion/RegularJeans-2.webp",
      "/assets/fashion/RegularJeans-3.webp",
      "/assets/fashion/RegularJeans-4.webp",
    ],
    Count: 1,
    Heading: "Men Loose Fit Mid Rise Blue Jeans",
    Brand: "Mufti",
    Type: "Fashion",
    Trending: true,
    Rating: "4.5",
    Description:
      "Stay warm and fashionable with our premium men's jacket. Designed for comfort and versatility, this jacket is crafted from high-quality materials to keep you cozy during chilly days.",
  },
  {
    Id: 28,
    Name: "Regular Jeans",
    Price: 1399,
    Category: "Jeans",
    Image: [
      "/assets/fashion/JeansBlue-1.webp",
      "/assets/fashion/JeansBlue-2.webp",
      "/assets/fashion/JeansBlue-3.webp",
      "/assets/fashion/JeansBlue-4.webp",
    ],
    Count: 1,
    Heading: "Men Loose Fit Mid Rise Blue Jeans",
    Brand: "Sparks",
    Type: "Fashion",
    Trending: true,
    Rating: "5.0",
    Description:
      "Stay warm and fashionable with our premium men's jacket. Designed for comfort and versatility, this jacket is crafted from high-quality materials to keep you cozy during chilly days.",
  },
  {
    Id: 29,
    Name: "Cargo Black Jeans",
    Price: 849,
    Category: "Cargo",
    Image: [
      "/assets/fashion/CargoBlack-1.webp",
      "/assets/fashion/CargoBlack-2.webp",
      "/assets/fashion/CargoBlack-3.webp",
    ],
    Count: 1,
    Heading: "Men Cargos",
    Brand: "Mufti",
    Type: "Fashion",
    Trending: false,
    Rating: "3.6",
    Description:
      "Stay warm and fashionable with our premium men's jacket. Designed for comfort and versatility, this jacket is crafted from high-quality materials to keep you cozy during chilly days.",
  },
  {
    Id: 30,
    Name: "Cargo Blue Jeans",
    Price: 940,
    Category: "Cargo",
    Image: [
      "/assets/fashion/CargoBlue-1.webp",
      "/assets/fashion/CargoBlue-2.webp",
      "/assets/fashion/CargoBlue-3.webp",
      "/assets/fashion/CargoBlue-4.webp",
    ],
    Count: 1,
    Heading: "Men Cargos",
    Brand: "Sparks",
    Type: "Fashion",
    Trending: false,
    Rating: "3.9",
    Description:
      "Stay warm and fashionable with our premium men's jacket. Designed for comfort and versatility, this jacket is crafted from high-quality materials to keep you cozy during chilly days.",
  },
  {
    Id: 31,
    Name: "Cargo Brown Jeans",
    Price: 449,
    Category: "Cargo",
    Image: [
      "/assets/fashion/CargoBrown-1.webp",
      "/assets/fashion/CargoBrown-2.webp",
      "/assets/fashion/CargoBrown-4.webp",
    ],
    Count: 1,
    Heading: "Men Cargos",
    Brand: "Sparks",
    Type: "Fashion",
    Trending: false,
    Rating: "4.9",
    Description:
      "Stay warm and fashionable with our premium men's jacket. Designed for comfort and versatility, this jacket is crafted from high-quality materials to keep you cozy during chilly days.",
  },
  {
    Id: 32,
    Name: "Cargo Green Jeans",
    Price: 1149,
    Category: "Cargo",
    Image: [
      "/assets/fashion/CargoGreen-1.webp",
      "/assets/fashion/CargoGreen-2.webp",
      "/assets/fashion/CargoGreen-3.webp",
      "/assets/fashion/CargoGreen-4.webp",
    ],
    Count: 1,
    Heading: "Men Cargos",
    Brand: "Sparks",
    Type: "Fashin",
    Trending: true,
    Rating: "3.1",
    Description:
      "Stay warm and fashionable with our premium men's jacket. Designed for comfort and versatility, this jacket is crafted from high-quality materials to keep you cozy during chilly days.",
  },
];